export const PROBLEMS = [
  {
    slug: 'two-sum',
    title: 'Two Sum',
    difficulty: 'Easy',
    tags: ['Array', 'Hash Map'],
    solved: true,
    acceptance: 62,
    timeLimitMs: 1000,
    memoryLimitMb: 256,
    description:
      'Given an array of integers `nums` and an integer `target`, return the indices of the two numbers such that they add up to `target`. You may assume each input has exactly one solution, and you may not use the same element twice.',
    constraints: ['2 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9', 'Exactly one valid answer exists.'],
    examples: [
      { input: 'nums = [2,7,11,15], target = 9', output: '[0,1]', explanation: 'nums[0] + nums[1] == 9, so return [0, 1].' },
      { input: 'nums = [3,2,4], target = 6', output: '[1,2]' },
    ],
    hints: ['A brute-force check is O(n^2) — can you do better with a hash map?', 'For each number, check if target - number has already been seen.'],
  },
  {
    slug: 'longest-substring',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    tags: ['String', 'Sliding Window'],
    solved: false,
    acceptance: 41,
    timeLimitMs: 1000,
    memoryLimitMb: 256,
    description: 'Given a string `s`, find the length of the longest substring without repeating characters.',
    constraints: ['0 <= s.length <= 5 * 10^4', 's consists of English letters, digits, symbols and spaces.'],
    examples: [
      { input: 's = "abcabcbb"', output: '3', explanation: 'The answer is "abc", with length 3.' },
      { input: 's = "bbbbb"', output: '1' },
    ],
    hints: ['Use a sliding window with two pointers.', 'Track the last seen index of each character.'],
  },
  {
    slug: 'merge-intervals',
    title: 'Merge Intervals',
    difficulty: 'Medium',
    tags: ['Array', 'Sorting'],
    solved: false,
    acceptance: 46,
    timeLimitMs: 1000,
    memoryLimitMb: 256,
    description: 'Given an array of intervals, merge all overlapping intervals and return an array of the non-overlapping intervals that cover all the intervals in the input.',
    constraints: ['1 <= intervals.length <= 10^4'],
    examples: [{ input: 'intervals = [[1,3],[2,6],[8,10],[15,18]]', output: '[[1,6],[8,10],[15,18]]' }],
    hints: ['Sort by start time first.'],
  },
  {
    slug: 'valid-parentheses',
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    tags: ['Stack', 'String'],
    solved: true,
    acceptance: 71,
    timeLimitMs: 1000,
    memoryLimitMb: 256,
    description: 'Given a string `s` containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid.',
    constraints: ['1 <= s.length <= 10^4'],
    examples: [{ input: 's = "()[]{}"', output: 'true' }, { input: 's = "(]"', output: 'false' }],
    hints: ['A stack is a natural fit for matching pairs.'],
  },
  {
    slug: 'course-schedule',
    title: 'Course Schedule',
    difficulty: 'Hard',
    tags: ['Graph', 'Topological Sort'],
    solved: false,
    acceptance: 28,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    description: 'There are `numCourses` courses labeled 0 to numCourses - 1. Given prerequisite pairs, determine if it is possible to finish all courses.',
    constraints: ['1 <= numCourses <= 2000'],
    examples: [{ input: 'numCourses = 2, prerequisites = [[1,0]]', output: 'true' }],
    hints: ['This is cycle detection in a directed graph.'],
  },
  {
    slug: 'lru-cache',
    title: 'LRU Cache',
    difficulty: 'Medium',
    tags: ['Design', 'Hash Map'],
    solved: false,
    acceptance: 38,
    timeLimitMs: 1000,
    memoryLimitMb: 256,
    description: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache with O(1) get and put.',
    constraints: ['1 <= capacity <= 3000'],
    examples: [{ input: 'capacity = 2, ["put",1,1], ["put",2,2], ["get",1]', output: '[null, null, 1]' }],
    hints: ['Combine a hash map with a doubly linked list.'],
  },
];

export const getProblemBySlug = (slug) => PROBLEMS.find((p) => p.slug === slug);
